on:
  push:
    branches:
      - main
    paths: ["**/index.ts"]

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        run: echo "This step will be skipped on Monday and Wednesday"
